### ISSUE TITLE
Prediction done but without output 

### ISSUE THREAD

**Issue by cogitas3d** [MathieuLeclercq/SlicerJawSegmentation#33]
Dear developers,

I install and follow the step-by-step present on publications, github and video. Apparently the system works, but doesnt generate output data.

![Captura de tela de 2024-12-01 16-52-37](https://github.com/user-attachments/assets/8ec1b5cf-8838-44c1-a253-dcdd8846203c)

I also have the conseole output:

> /home/cogitas3d/Programs/SlicerDentalModelSeg-main/Models/dental_models/upper.stl
Select file
/home/cogitas3d/Programs/OrtogOnBlender_XP/Slicer-5.6.2-linux-amd64/bin/Python/slicer/util.py:2786: UserWarning: does not have observer
  warn("does not have observer")
Distribution    Found for shapeaxi
dentalmodelseg_path :  /home/cogitas3d/Programs/OrtogOnBlender_XP/Slicer-5.6.2-linux-amd64/bin/../lib/Python/bin/dentalmodelseg
parameters :  {'surf': '/home/cogitas3d/Programs/SlicerDentalModelSeg-main/Models/dental_models/upper_P1.vtk', 'input_csv': 'None', 'out': '/home/cogitas3d/Programs/SlicerDentalModelSeg-main/Models/dental_models', 'overwrite': '0', 'model': '/home/cogitas3d/Programs/SlicerDentalModelSeg-main/Models/pth/07-21-22_val-loss0.169.pth', 'crown_segmentation': '0', 'array_name': 'Universal_ID', 'fdi': '0', 'suffix': 'predict', 'vtk_folder': 'None', 'dentalmodelseg_path': '/home/cogitas3d/Programs/OrtogOnBlender_XP/Slicer-5.6.2-linux-amd64/bin/../lib/Python/bin/dentalmodelseg'}
PROCESS DONE.
Process completed successfully.
************************* Output cli *************************
Starting crownsegmentation cli
args :  Namespace(surf='/home/cogitas3d/Programs/SlicerDentalModelSeg-main/Models/dental_models/upper_P1.vtk', input_csv='None', out='/home/cogitas3d/Programs/SlicerDentalModelSeg-main/Models/dental_models', overwrite='0', model='/home/cogitas3d/Programs/SlicerDentalModelSeg-main/Models/pth/07-21-22_val-loss0.169.pth', crown_segmentation='0', array_name='Universal_ID', fdi='0', suffix='predict', vtk_folder='None', dentalmodelseg_path='/home/cogitas3d/Programs/OrtogOnBlender_XP/Slicer-5.6.2-linux-amd64/bin/../lib/Python/bin/dentalmodelseg')
start crown segmentation cli
_________________________ RUN_IN_LINUX _________________________
command :  []
Output :  [96m Start prediction of your data [0m

> Error :  Traceback (most recent call last):
  File "/home/cogitas3d/Programs/OrtogOnBlender_XP/Slicer-5.6.2-linux-amd64/bin/../lib/Python/bin/dentalmodelseg", line 8, in <module>
    sys.exit(cml())
  File "/home/cogitas3d/Programs/OrtogOnBlender_XP/Slicer-5.6.2-linux-amd64/lib/Python/lib/python3.9/site-packages/shapeaxi/dental_model_seg.py", line 265, in cml
    main(args)
  File "/home/cogitas3d/Programs/OrtogOnBlender_XP/Slicer-5.6.2-linux-amd64/lib/Python/lib/python3.9/site-packages/shapeaxi/dental_model_seg.py", line 26, in main
    model = saxi_nets.DentalModelSeg(custom_model=args.model, device=device)
AttributeError: module 'shapeaxi.saxi_nets' has no attribute 'DentalModelSeg'

Thank you for your time and consideration.

**Comment by thsmit** [comment]
Same error for me. On linux as well.

**Comment by cpinter** [comment]
Is this project still active? I tried running the module on Linux on Slicers 5.6.2, 5.7, 5.2.1. Did not work with any versions. Also there is no response to any comment from the community. Should we consider this project dead? Would be useful information on its own. Thank you!

**Comment by thsmit** [comment]
Hi @cpinter 

I am using it with 5.7.

I think you need to change: 

model = saxi_nets.DentalModelSeg(custom_model=args.model, device=device) to 
model = saxi_nets.DentalModelSeg_lightning(custom_model=args.model, device=device)

**Comment by algadm** [comment]
Sorry for the late response!

About three weeks ago, we updated the code to use SlicerConda on Linux due to issues with the PyTorch3D installation and are now restricting it to ShapeAxi 1.0.10.
In this version, we use `model = saxi_nets_lightning.DentalModelSeg(custom_model=args.model, device=device)`, which seems to work well.
Let me know if you are still encountering this issue!

**Comment by thsmit** [comment]
Yes, saxi_nets_lightning works well

**Comment by algadm** [comment]
Glad to hear it's working now! I'll go ahead and close this issue, but feel free to reopen if anything comes up.
